---
- functions:
  - {name: unsafePerformIO, within: []}
  - {name: error, within: [Development.Shake.ATS, Language.ATS.Generate, Development.Shake.Linters, Development.Shake.C]}  # throw real errors
  - {name: undefined, within: [Language.ATS.PrettyPrint, Main, Language.ATS.Package.Dependency, Language.ATS.Generate, Language.ATS.Package.Build, Development.Shake.ATS, Language.ATS.Types, Development.Shake.ATS.Generate, Development.Shake.ATS.Rules]}
  - {name: fromJust, within: [Language.ATS.Generate]}
  - {name: foldl, within: []}

- error: {lhs: "hylo embed", rhs: "ana", name: "Use anamorphism"}
- error: {lhs: "hylo f project", rhs: "cata f", name: "Use catamorphism"}
- error: {lhs: "do { x <- y ; pure (f x) }", rhs: "f =<< y", name: "Avoid do-notation"}
- error: {lhs: "concat", rhs: "join", name: "Generalize concat"}
- error: {lhs: "concatMap", rhs: "(=<<)", name: "Generalize concatMap"}
- error: {lhs: "f >> pure ()", rhs: "void f", name: "Use void"}
- error: {lhs: "over _1 f x", rhs: "first f x", name: "Use arrows"}
- error: {lhs: "over _2 f x", rhs: "second f x", name: "Use arrows"}
- error: {lhs: "bool x x p", rhs: "x", name: "Avoid bool"}

- ignore: {name: Use <$>, within: [Language.ATS.PrettyPrint]}
- ignore: {name: Unused LANGUAGE pragma, within: [Language.ATS.PrettyPrint]}
- ignore: {name: Functor law, within: [Language.ATS.PrettyPrint]}
- ignore: {name: Evaluate, within: [Language.ATS.Generate]}
- ignore: {name: Use foldr}
