---

build: off

before_test:
  - choco install ghc
  - choco install cabal
  - set PATH=C:\Program Files\Git\mingw64\bin;%PATH%

clone_folder: "c:\\stack"
environment:
  global:
    STACK_ROOT: "c:\\sr"

test_script:
  - set path=%PATH%;C:\Users\appveyor\AppData\Roaming\local\bin
  - cabal new-build
  - type C:\stack\.stack-work\logs\alex-3.2.4.log
  - ps: Get-ChildItem . -name -recurse madlang.exe
  - ps: Copy-Item c:\\stack\\.stack-work\\install\\81831b05\\bin\\atspkg.exe atspkg-x86_64-pc-windows.exe
  - ps: Push-AppveyorArtifact atspkg-x86_64-pc-windows.exe

deploy:
  artifacts: atspkg-x86_64-pc-windows.exe
  provider: GitHub
  on:
    appveyor_repo_tag: true
  auth_token:
    secure: cNzi4ZEE4PIrKxBJXEDPHkqrHI4fdSJtIQZ8n7qbYJwBtsx8TkBxduK8eIr6fzdY

branches:
  only:
    - master
    - /\d+\.\d+\.\d+\.\d+.*$/
