---
resolver: lts-10.3
packages:
  - '.'
extra-deps:
  - shake-ext-1.4.0.1
  - shake-ats-0.1.0.4
  - composition-prelude-1.1.0.2
  - language-ats-0.1.1.5
flags:
  ats-pkg:
    development: false
extra-package-dbs: []
