---
resolver: lts-10.7
packages:
  - 'ats-pkg'
  - 'language-ats'
  - 'ats-format'
  - 'shake-ext'
  - 'shake-ats'
  - 'dependency'
  - 'hs2ats'
extra-deps:
  - dhall-1.10.0
  - composition-prelude-1.3.0.4
  - cli-setup-0.2.0.1
  - hspec-dirstream-0.3.0.0
  - dirstream-1.0.3
  - prettyprinter-1.2.0.1
  - htoml-megaparsec-1.1.0.1
flags:
  ats-pkg:
    development: false
extra-package-dbs: []
