---
resolver: lts-10.4
packages:
  - '.'
extra-deps:
  - shake-ext-2.1.0.2
  - shake-ats-1.1.0.2
  - composition-prelude-1.1.0.2
  - language-ats-0.1.1.17
  - cli-setup-0.2.0.1
  - hs2ats-0.2.0.4
flags:
  ats-pkg:
    development: false
extra-package-dbs: []
