---
resolver: lts-11.1
packages:
  - 'ats-pkg'
  - 'language-ats'
  - 'ats-format'
  - 'shake-ext'
  - 'shake-ats'
  - 'dependency'
  - 'hs2ats'
extra-deps:
  - composition-prelude-1.3.0.4
  - Cabal-2.2.0.0
  - cli-setup-0.2.0.1
  - hspec-dirstream-0.4.0.0
  - dirstream-1.0.3
  - htoml-megaparsec-1.1.0.1
flags:
  ats-pkg:
    development: false
  hs2ats:
    no-executable: false
extra-package-dbs: []
