---
resolver: lts-10.4
packages:
  - '.'
extra-deps:
  - shake-ext-1.4.0.3
  - shake-ats-0.2.0.4
  - composition-prelude-1.1.0.2
  - language-ats-0.1.1.7
  - cli-setup-0.1.0.3
flags:
  ats-pkg:
    development: false
extra-package-dbs: []
