---
resolver: nightly-2018-04-28
packages:
  - 'ats-pkg'
  - 'language-ats'
  - 'ats-format'
  - 'shake-ext'
  - 'shake-ats'
  - 'dependency'
  - 'hs2ats'
  - 'cdeps'
extra-deps:
  - composition-prelude-1.4.0.3
  - bzlib-0.5.0.5
  - casing-0.1.4.0
  - cli-setup-0.2.0.4
  - hspec-dirstream-1.0.0.0
  - dirstream-1.0.3
  - htoml-megaparsec-1.1.0.4
flags:
  hs2ats:
    no-executable: false
  cdeps:
    no-executable: false
extra-package-dbs: []
